### ISSUE TITLE
`character(len=*)` underlined as an error when len is a declared variable elsewhere.

### ISSUE THREAD

**Issue by blaylockbk** [fortran-lang/fortls#173]
> Originally Discussed Here: https://github.com/fortran-lang/vscode-fortran-support/discussions/574

**Describe the bug**
I have a subroutine in a large code base. I get an underlined error indicator for `character(len=10)` when there happens to be a variable `len` declared elsewhere. When I hover over the error underlining, the message says `Object "len" not found in scope` and then gives the name of the file where the variable `len` is declared as an object.

![image](https://user-images.githubusercontent.com/6249613/179308459-46c68a60-1294-40a3-b2b2-70353114594b.png)

The "len" statemen inside a character declaration should never refer to a declared variable named len, right? This may be a bug in fortls.

**Comment by gnikit** [comment]
This is the MWE to replicate it


```fortran
module foo
  character(len=100), parameter :: TEST = "4.10.4"
end module foo

program main
  use foo
  integer :: len
end program main
```
