### ISSUE TITLE
bug: Modern Fortran throws an error when typing `submodule()`

### ISSUE THREAD

**Issue by zoziha** [fortran-lang/fortls#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When entering `submodule()`, `Modern Fortran` will report an error, as shown in the following figure:
(This doesn't seem to be that serious, if I ignore it and keep typing the code, everything works fine in `Modern Fortran`.)

![fortran](https://user-images.githubusercontent.com/32035096/183984293-4cd1dc04-f9bb-43cb-876c-6ca46124ba03.gif)

### Screenshots

![image](https://user-images.githubusercontent.com/32035096/183982861-ce950872-6111-4d93-9ace-7fe51ff3fdad.png)

```sh
Change request failed for file 
'C:\Users\zoziha\com.zoziha\fortran\tmp\demo\app\demo.f90': Error during parsing
```

### Expected Behaviour

Type `submodule()` and `Modern Fortran` will not report an error.

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.70.0

### Platform and Architecture

Windows

### Additional Information

Thank you so much for maintaining Modern Fortran, @gnikit ! ❤

**Comment by gnikit** [comment]
Apologies @zoziha for taking some time to get to this. This was actually a cluster of bugs that I have since fixed.
