### ISSUE TITLE
Kind parameter not recognized when loaded from module

### ISSUE THREAD

**Issue by jalvesz** [fortran-lang/fortls#262]
**Describe the bug**
Looking at https://github.com/jacobwilliams/json-fortran/blob/master/src/tests/jf_test_01.F90
An error is promted at double precision declarations such as:
![image](https://user-images.githubusercontent.com/102541118/218270194-3db149c2-fca8-4a3b-8a5c-c1dd27b0b34b.png)

wp is loaded from a module by
`module jf_test_1_mod`
`    use json_module, wp => json_RK, IK => json_IK, LK => json_LK`

several files within the project have the same message since this import pattern is repeated several times

**Expected behavior**
In principle no warning or error should be prompted since this declaration is allowed by the language

**Setup information (please complete the following information):**
 - OS: [Windows11]
 - Python Version [e.g. 3.9.6]
 - fortls Version [e.g. 2.3]
 - Code editor used [VS Code]
 - the Fortran extension for the code editor and its version [e.g. Modern Fortran v3.4.2023020701]

**Configuration information (please complete the following information):**
No special json settings added

**Comment by gnikit** [comment]
Hi @jalvesz as far as I can tell this is no longer the case, and I can't replicate with v3.0.0. Let me know if you still get this and I'll reopen.
