### ISSUE TITLE
Semicolon after END [IF/DO/...] triggers "Unexpected end of scope"

### ISSUE THREAD

**Issue by OttTs** [fortran-lang/fortls#265]
**Description**
Semicolons after `END IF`/`END DO`/... statements produce an "Unexpected end of scope" error.

**Screenshot**
![image](https://user-images.githubusercontent.com/95188030/223401742-859eef6d-30cf-4255-a123-3872c14d0b03.png)

**Comment by gnikit** [comment]
## MWE

```f90
program semicolon_test
    implicit none
    integer :: i
    do i=1, 3
        print *, "Hello World!"
    end do;
end program semicolon_test
```
