### ISSUE TITLE
bug: Error hovering an associated function

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/fortls#269]
When I use the Modern Fortran plugin in VSCode and hover `hi` in this little piece of code:

```fortran
program main
  implicit none

  associate (hi => say_hi())
    if (hi) print *, 'Bye'
  end associate

contains

  logical function say_hi()
    print *, 'Hi'
    say_hi = .true.
  end

end program
```

I get this error message:

<img width="466" alt="Screenshot 2023-03-19 at 22 51 04" src="https://user-images.githubusercontent.com/43783196/226211842-fe75d7ed-c468-4502-b516-9990c4d21861.png">

The program, however, runs normally and prints:

```bash
Hi
Bye
```

**Specs**

- macOS Ventura `13.2.1`, M1
- Visual Studio Code `1.76.2`
- Modern Fortran `v3.2.0`, but the same is observed on the pre-release version `v3.4.2023030801`
- fortls `2.13.0`, installed via Homebrew
- Python `3.11.2`

Related Issues: https://github.com/fortran-lang/fortls/issues/214, https://github.com/fortran-lang/fortls/issues/108

**Comment by gnikit** [comment]
I completely missed this @minhqdao, will have a look

**Comment by gnikit** [comment]
Traceback:

```log
Traceback (most recent call last):
  File "/home/gn/Code/Python/fortls/venv/bin/fortls", line 8, in <module>
    sys.exit(main())
  File "/home/gn/Code/Python/fortls/fortls/__init__.py", line 45, in main
    debug_server_general(args, vars(args))
  File "/home/gn/Code/Python/fortls/fortls/__init__.py", line 290, in debug_server_general
    hover_results = s.serve_hover(
  File "/home/gn/Code/Python/fortls/fortls/langserver.py", line 1111, in serve_hover
    var_obj.get_hover_md(long=True).replace(
  File "/home/gn/Code/Python/fortls/fortls/objects.py", line 1810, in get_hover_md
    return fortran_md(*self.get_hover(long, drop_arg))
  File "/home/gn/Code/Python/fortls/fortls/objects.py", line 1801, in get_hover
    hover_str = ", ".join([self.get_desc()] + self.get_keywords())
  File "/home/gn/Code/Python/fortls/fortls/objects.py", line 1817, in get_keywords
    return get_keywords(self.link_obj.keywords, self.link_obj.keyword_info)
AttributeError: 'Function' object has no attribute 'keyword_info'
```

**Comment by Carltoffel** [comment]
> I completely missed this @minhqdao, will have a look

Was the bug I mentioned related, or should I open a new bug report? :)

**Comment by gnikit** [comment]
Hey @Carltoffel so there is a difference in the hover signatures, but you can always see the documentation.
![Screenshot from 2023-05-17 10-37-25](https://github.com/fortran-lang/fortls/assets/16143716/91be339a-63eb-4bb2-b101-481529e119cf)
![Screenshot from 2023-05-17 10-39-25](https://github.com/fortran-lang/fortls/assets/16143716/1b78f64e-8930-42c5-a504-efe2f2be5262)

**Comment by Carltoffel** [comment]
Ah, thanks. Then it probably is a problem with the LSP implementation in neovim.

**Comment by gnikit** [comment]
The inconsistency between the 2 docstrings is tracked in https://github.com/fortran-lang/fortls/issues/281.

**Comment by gnikit** [comment]
I will try and issue a pre-release for v3.0.0 for people to be able to download from PyPi (although the pre-release version will still have a lower precedence over the stable releases, so it won't be installed automatically).

In the meantime you can try the latest fortls version which includes *a bunch* of bug fixes, performance improvements and a new Markdown docstring parser via:

```sh
pip install git+https://github.com/fortran-lang/fortls.git
```

**Comment by Carltoffel** [comment]
Thank you!
I'm not sure if I installed the correct version (2.13.1.dev156+g6a82432) but it looks better now:

![image](https://github.com/fortran-lang/fortls/assets/33249047/dd7615eb-6d3f-4ba3-81d3-601b9ac0229a)

However, the format is still messed up.

**Comment by gnikit** [comment]
So the new hover results, take the docstrings and assemble them in markdown. Then the client (VSCode, neovim, Emacs, etc. ) Is meant to render that markdown. Not sure why neovim is lagging behind on that https://www.reddit.com/r/neovim/comments/tx40m2/is_it_possible_to_improve_lsp_hover_look/

Currently there is no way to use the old style docs (it was to expensive to maintain both types of docs assembly processes).
