### ISSUE TITLE
Incomplete hover of parameters variables

### ISSUE THREAD

**Issue by gbogopolsky** [fortran-lang/fortls#284]
**Describe the bug**
When hovering over a variable that was defined as a computed `parameter`, only the first member of the computation shows up

**To Reproduce**
Define a computed parameter, use it in the code and hover over it.
If there is a space or "/" in the parameter definition, anything after will not show up.

```fortran
real(8), parameter :: three = 1.0d0*3.0d0
real(8), parameter :: six = 2.0d0 * 3.0d0
real(8), parameter :: one = 1.0d0
real(8), parameter :: sixth = one / six
real(8), parameter :: third = one/three
```
On Hovering, one gets the following:

![image](https://github.com/fortran-lang/fortls/assets/25324757/c4814ae9-e4f9-4ce0-a82e-771f83c7709f)
![image](https://github.com/fortran-lang/fortls/assets/25324757/9a1a9895-96ea-458a-b18e-0bfac0d41744)
![image](https://github.com/fortran-lang/fortls/assets/25324757/ab9dec06-aa64-4af5-a683-ee0d0d43c95a)
![image](https://github.com/fortran-lang/fortls/assets/25324757/6a6e2ea2-3d01-4d86-806c-850bcf53600b)
![image](https://github.com/fortran-lang/fortls/assets/25324757/42c89682-30c7-49fa-8f17-aabd3a1527d5)

Except when there is a "*" without spaces, the second term of the computed parameter is always missing.

**Expected behavior**
I would expect the whole line to show up, until an endline character or the start of a comment.

**Setup information (please complete the following information):**
 - OS: Mac with Linux SSH Server
 - Python 3.8.1
 - fortls 2.13.0
 - VS Code
 - Modern Fortran v3.4.2023051701

**Comment by folk85** [comment]
I suggest the solution of this bug. Add several tests. But `pytest -v` failed in one test `test/test_interface.py::test_version_update_pypi`.
