### ISSUE TITLE
bug: hover multi-line parameter signature

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/fortls#291]
Introduced via https://github.com/fortran-lang/fortls/pull/288

<img width="472" alt="image" src="https://github.com/fortran-lang/fortls/assets/16143716/0b12d075-6484-444b-bc05-36240715283c">

The ideal resolution would be to trim the forward and trailing whitespaces for PARAMETER_VAL.

_Originally posted by @gnikit in https://github.com/fortran-lang/fortls/pull/288#pullrequestreview-1475638915_

**Comment by folk85** [comment]
@gnikit, I suggest one solution, but I'm not sure that it is the correct place for implementation.
