### ISSUE TITLE
Add configurations via `settings` option in `setup()`

### ISSUE THREAD

**Issue by baco** [fortran-lang/fortls#298]
**Is your feature request related to a problem? Please describe.**
Most of the LSP servers are configured via settings exposed in a `settings` table that is later passed as an argument of the `setup()` constructor. `fortls` achieves this behavior by directly adding the flags to the `config.cmd` attribute which is intended to have a string to a standalone executable (either absolute, or relative to `$PATH` dirs), not a command line with flags.

**Describe the solution you'd like**
It would be useful to have settings set by the `settings` options of the `setup` constructor (to make the interface uniform to other LSP servers as well) and make LSP server handle the command line building from there.

**Comment by gnikit** [comment]
There is no agreed upon interface for passing options to language servers, some use tables, some use config files, some use clis and some use combinations of the above. What is the improvement of the proposed design? Can you be more specific in your suggestion?
