### ISSUE TITLE
Consider `setuptools_scm`

### ISSUE THREAD

**Issue by fosskers** [fortran-lang/fortls#326]
**Describe the bug**

https://pypi.org/project/setuptools-scm-git-archive/, as introduced in #44,  is unfortunately deprecated. It is suggested that `setuptools_scm` is used instead.

This was brought to my attention by a [downstream user](https://aur.archlinux.org/packages/fortls#comment-937589), so I'm passing the suggestion along. 

Thank you for your time.

**Comment by gnikit** [comment]
We don't use `.git_archival.txt` other than removing the dependency and using and pinning the lower version is there something else that needs to be done?

**Comment by fosskers** [comment]
According to https://github.com/Changaco/setuptools_scm_git_archive#migration-guide that should be sufficient?
