### ISSUE TITLE
bug (autocompletion): subroutines are shown as functions, and only the name is autocompleted, without the argument list.

### ISSUE THREAD

**Issue by aerosayan** [fortran-lang/fortls#354]
**Describe the bug**
Autocomplete doesn't seem to work correctly all of a sudden, for some reason.
Subroutines are shown as functions, and only the name is autocompleted.
The subroutine/function argument list is not displayed at all.

**To Reproduce**
_I have no idea how to reproduce this._
Either something went wrong in my configuration, or it's an internal bug in fortls.
Anyways, I'm just reporting this, in case others also face similar issues, then you'll know something internal in fortls has gone wrong.

**Screenshots & Animations**
![bug-1](https://github.com/fortran-lang/fortls/assets/39849461/82ef51ac-0281-41c7-b986-07c24755c77e)
![bug-2](https://github.com/fortran-lang/fortls/assets/39849461/49f59e31-d74e-44ac-8733-7c9d0f34f30b)
![bug-3](https://github.com/fortran-lang/fortls/assets/39849461/10d8ddf2-9b35-48ca-bcd1-b3cb345f82a2)

**Setup information (please complete the following information):**
 - OS: Linux
 - Python Version: ` python --version` produces `Python 2.7.18`, and `python3 --version` produces `Python 3.8.2`
 - fortls Version: 2.13.0 (installed by Mason in neovim)
 - Code editor used : neovim

**Configuration information (please complete the following information):**
Neovim starts fortls with command: ` fortls --notify_init --hover_signature --hover_language=fortran --use_signature_help`

My fortls configuration is:
```json
{
   "nthreads": 4,
   "notify_init": true,
   "incremental_sync": false,
   "sort_keywords": false,
   "disable_autoupdate": false,
   "debug_log": false,

   "source_dirs": ["./src/**"],
   "incl_suffixes": [],
   "excl_suffixes": [],
   "excl_paths": [],

   "autocomplete_no_prefix": false,
   "autocomplete_no_snippets": false,
   "autocomplete_name_only": false,
   "lowercase_intrinsics": true,
   "use_signature_help": true,

   "hover_signature": false,
   "hover_language": "fortran90",

   "max_line_length": -1,
   "max_comment_line_length": -1,
   "disable_diagnostics": false,

   "pp_suffixes": [],
   "include_dirs": [],
   "pp_defs": {},

   "symbol_skip_mem": false,

   "enable_code_actions": false
}
```

**Comment by gnikit** [comment]
Can you post a MWE of the code that demonstrates it. What is the output of:

```sh
fortls --debug_filepath your-file-name --debug_completion --debug_line your-lin-num --debug_char your_column_num
```

**Comment by aerosayan** [comment]
Well, the LSP autocompletion is working correctly again after I restarted my terminal.

No idea what caused the bug, or what fixed it.

![result](https://github.com/fortran-lang/fortls/assets/39849461/1cb30abf-c2c9-42e2-a55e-4f1125e4309c)

**Comment by gnikit** [comment]
I am closing this issue. In the future please try and narrow down the scope of the problem and form a MWE before opening a bug report.
