### ISSUE TITLE
Python -> Fortran

### ISSUE THREAD

**Issue by jordan4ibanez** [fortran-lang/fortls#436]
**Is your feature request related to a problem? Please describe.**
Performance. I use fortran daily, it's pretty dang quick. Maybe we could shift a lot of that python code into fortran and give this thing a massive performance kick.

**Describe the solution you'd like**
Translate the python code into fortran so it's a few dozen times faster.

**Describe alternatives you've considered**
We could always use C. (lol)

**Additional context**
Starts chugging with large projects.

**Comment by gnikit** [comment]
This is outside of the scope of this project, for numerous reasons. However, another language server written in Fortran would be welcome, although I would be cautious with the expected performance gains. The bottlenecks in fortls are independent of the language used and more to do with the algorithms and how I wrote them. I am closing this Issue, but feel free to start a Discussion either here or in Fortran-lang.
