### ISSUE TITLE
Add support for GoTo Implementation in submodules

### ISSUE THREAD

**Issue by gha3mi** [fortran-lang/fortls#74]
fortls can detect the interface in a module, but not its implementation in a submodule, see this example.

```f08
MODULE MOD

IMPLICIT NONE

!==============================================================================
TYPE :: TYP
    REAL(KIND=8) :: value
CONTAINS
    PROCEDURE :: PRC1 => PRC_PRC1
END TYPE TYP
!==============================================================================


!==============================================================================
INTERFACE
    MODULE  SUBROUTINE PRC_PRC1(this)

        IMPLICIT NONE

        CLASS(TYP), INTENT(INOUT) :: this

    END SUBROUTINE PRC_PRC1
END INTERFACE
!==============================================================================

END MODULE MOD

```
```f08
SUBMODULE(MOD) SMOD

IMPLICIT NONE

CONTAINS

!==============================================================================
MODULE SUBROUTINE PRC_PRC1(this)

    IMPLICIT NONE

    CLASS(TYP), INTENT(INOUT) :: this

    this%value = 0

END SUBROUTINE PRC_PRC1
!==============================================================================

END SUBMODULE SMOD
```

**Comment by gnikit** [comment]
Could you please elaborate as to what `fortls` is currently doing and what the expected behaviour should be?

**Comment by gha3mi** [comment]
In this example, go to definition (F12) for procedure `PRC_PRC1` can find the `module subroutine PRC_PRC1` in the interface, but not the implementation of `module subroutine PRC_PRC1` in submodule `SMOD`, also fortls does not give any information about the implementation of the procedure `PRC_PRC1` in the submodule `SMOD`.

**Comment by gnikit** [comment]
I see what you mean. I think both issues that you are mentioning are effectively the same. GoTo Implementation does not detect the implementation for `submodules`.

I will look into it, thanks!

**Comment by gnikit** [comment]
This has turned out to be a bit tricker that what I originally thought. Since the object associated with the interface does not hold a reference to the object with the implementation. I will have to redesign some bits but I think it is doable.

**Comment by gha3mi** [comment]
Hi @gnikit, I would like to ask you if there is a plan for this issue?

**Comment by gnikit** [comment]
I started to work on it, but then I encountered a series of other bugs along the way with the parser and constants so I got side-tracked. Right now I am slightly busy with PhD work, so it might be a while until I get to this.

I am making a project with the most critical bugs to fix, I will try to have a look at this end of day today, but people are also invited to try and help.

**Comment by gha3mi** [comment]
Thank you for your reply, I am also very busy at the moment. I will try to contribute when I find some free time.
